apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retool-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://your-git-repo-url.com'  # URL of your Git repository
    targetRevision: HEAD                      # Branch, tag, or commit of your repo
    path: path/to/your/values                # Directory in your repo containing values.yaml or other configs
    helm:
      parameters:                             # Optional: Helm parameters can also be specified if needed
        - name: someParameter
          value: someValue
      releaseName: my-retool-release
      valueFiles:
        - values.yaml                         # Name of your custom values file within the specified path
    chart:
      name: retool-chart                      # The name of the chart in the remote repository
      version: 1.0.0                          # The version of the chart you want to deploy
      repoURL: 'https://charts.retools.com'   # URL of the Helm chart repository
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: my-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
