apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retool-application
  namespace: argocd
spec:
  project: default
  sources:
    - chart: retool                    # The name of the chart in the external Helm repository
      targetRevision: 6.2.5                  # The version of the chart you want to deploy
      repoURL: 'https://charts.retool.com'  # URL of the Helm chart repository
      helm:
        valueFiles:
          - '$values/values.yaml'
    - repoURL:
        ref: values
        targetRevision: master
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: my-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
